### ISSUE TITLE
Dynamic highlight of selected code in text

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#102]
In the code text dialogue I think it would be really great if selecting a code in the tree somehow made the associated coded snippets on the right stand out (eg underlined text or something better) and vice versa -- ie clicking on the text on the right would make the associated code(s) on the left stand out. This would make a huge difference with 30+ codes where similar codes blend into each other.

**Comment by jdittrich** [comment]
One way could be to slightly darken the background color of the respective highlighted text. Thus, you use the current mode of signaling coding to the user via the background color. Underline works, too, I guess, but it introduces an additional mode of text formatting which you might want to use for other purposes.

**Comment by glocalglocal** [comment]
Slightly darkened background colour would not work if you used all available shades and text are heavily coded (like in my current project). Underline is less elegant and may not work well with dark highlight colours, particularly when the row below is coloured differently. How about dotted underline? A different colour text may be another way, but again that mode may be reserved for something else. Bold is already taken by Annotate (not sure about that myself TBH, because it causes text to be reflowed and may be required in the future for emphasis in the original text).   

I would vote for dotted underline if it looks OK and if it is possible.

**Comment by ccbogel** [comment]
Yes I think an underline of some sort is possible.

**Comment by ccbogel** [comment]
A selected code in the tree now underlines matching coded text in the textedit

**Comment by glocalglocal** [comment]
This already works fantastically well and it makes a huge difference. The freq column helps greatly too. Only issue is that as expected the underline is difficult to spot against dark highlights. I am not sure if this is possible at all without major work, but one way to solve this and improve general usability would be to show a vertical line or something in the margin telling you whereabout to look. Very useful also when you simply have lots of codings and you have to go hunting to find them. 

Another thing, probably much easier: when qualcoder shows the single or overlapping codings above the textbox, clicking on one of those labels could automatically select the code in the tree and show the underlined snippets for that code.

**Comment by ccbogel** [comment]
The vertical line is not possible for me at this time, it would be very difficult to do. There are other line styles (e.g. a wavy line or solid line).

The much easier thing - I am not getting exactly what you mean there.

**Comment by glocalglocal** [comment]
The wavy line may help then -- not sure. 

The much easier thing: This is not to do with the visibility problem. It's a related but separate issue. We click on text with overlapping codings. The codes used are shown as labels just above the text box. When you click on one of the labels, qualcoder could act as if you clicked on the corresponding code label in the tree: (a) display the selected code as 'Code:' above the tree pane (b) underline the corresponding snippets in the text. That could be done with whatever method you use in the future to display those labels.

**Comment by ccbogel** [comment]
Currently, that lable (top right) that displays the codename(s) is one label widget. so cannot click on one of two codenames listed there - it wont be recognised.

**Comment by glocalglocal** [comment]
Yes, but one day they may be made clickable. Or the label display functionality may even move to the tree. Who knows?

**Comment by ccbogel** [comment]
ok - I have made it so ther are 2 buttons, if text is clicked, then one or two buttons show the code. clicking on the buttons then selects that code

**Comment by glocalglocal** [comment]
I don't see 2 buttons or anything different. But I notice now a related issue. I code a sentence and it is highlighted in grey (not the usual blue for selected text) and underlined. It gets its proper code colour when I de-select the text by clicking elsewhere. When I select it again, the background colour is blue as it should.

**Comment by glocalglocal** [comment]
I see two button, but what if there are more relevant codes? I have an instance of four, only two are listed. 

Also, the extra long code description I mentioned (60 chars) means the description is truncated on those buttons. Inevitable with buttons, but the description is also centred, so text on both sides is cut off. 

Unfortunately, the wavy underline is less visible against dark backgrounds.

Having said all this, the more I try this out, being able to select a code to instantly get all the codings in the text makes a big difference.

**Comment by ccbogel** [comment]
OK I can probably add one more row for another button.
I did re-order the coded texts so that longer text segments are highlighted first -so that will reduce drowning out of shorter segments.
Unsure how to deal with long test on the buttons -  if I applied the tree font size - then more text will be visible.
will replace wavy with dashed underlines

**Comment by glocalglocal** [comment]
not drowning out: good idea. 

There must be situations where buttons with shorter labels can fit side-by-side, but that will be like solving a problem every time to find best fit. 

But of course in certain scenarios there will be more codings than 3, and space for buttons will always be scarce unless another pane pops up, slides sideways or something. In fact, search being permanently there takes a lot of space for something that may be used occasionally -- which is why applications hide it until needed. That could be extra space. 

The text is still centred. This looks like something that can be easily fixed (to avoid chopping off both beginning and end of long labels). 

Another thing: I click on a button to see codings. They are underlined. Then click on text elsewhere. Top right buttons change to reflect the codings of new text. But the old text remains underlined.

**Comment by ccbogel** [comment]
Another thing: I click on a button to see codings. They are underlined. Then click on text elsewhere. Top right buttons change to reflect the codings of new text. But the old text remains underlined.
Yes - this is because the code is highlighted in the tree- this is the reason the text will remain underlined.

**Comment by ccbogel** [comment]
have made 3 buttons. and made them wider with tooltips.
I am not sure how to otherwise resolve this space issue yet.

**Comment by jdittrich** [comment]
This, in general, seems to be a tricky issue which was also discussed over at taguette. Here is the [tread](https://gitlab.com/remram44/taguette/-/issues/126#note_191553937). 
The solution that seems to be user friendly and applied in some commercial software (MaxQDA, Quirkos) are (clickable/selectable) stripes/brackets at the left edge of the text: 
![image](https://user-images.githubusercontent.com/3416487/87254210-1e83c980-c481-11ea-8b77-7611e2b63a94.png)

While the button solutions certainly works, it is not easy to understand as buttons usually execute actions rather than selecting (text).

**Comment by glocalglocal** [comment]
Nvivo does the same, only using the right-hand margin instead and reserving space for that strip along the whole length of the document.  One problem with this approach is that I doubt the thin strips work well with more than the 9 colours NVivo supports. That's if the current text box implementation supports strips at all.

**Comment by ccbogel** [comment]
yeah I understand. coding stripes on the LHS will be difficult but not impossible to do. But  I dont think it really fixes the issue. As you could have 2 coding stripes showing for two discretely coded texts in a text row, and equally this would occur if you had 2 overlapping coded texts.
On consideration,  I will replace the buttons: give a label title of 'text codes at this position' a number of codes at this position and a combobox showing the specific codes (which will be selectable).

**Comment by jdittrich** [comment]
> and equally this would occur if you had 2 overlapping coded texts.

True. If this is important, one could consider underlines like in f4analyse, which also seems to have a quite nice UI.

> give a label title of 'text codes at this position' a number of codes at this position and 
> a combobox showing the specific codes (which will be selectable).

This makes sense. Maybe I have not fully gasped the useage here – what actions does "selecting a code" allow subsequently? If it is e.g. mainly about deleting one could also offer the functionality directly on the indicator of which codes are under the cursor, like this: 

![grafik](https://user-images.githubusercontent.com/3416487/87284227-6bee4e00-c4f6-11ea-83d1-75b05ac4ad15.png)

or, if there are many options possible, it could be: 

![grafik](https://user-images.githubusercontent.com/3416487/87285538-e79cca80-c4f7-11ea-8422-99a8aeefe5cb.png)

( I do not know if qt provides these widgets, but they are not this uncommon and often run as "tags" or "pills")

**Comment by ccbogel** [comment]
HI thanks.
Yes maybe I have not though this through well. Maybe these buttons or combobox are not really needed at all.
I do have right click context menu in the textedit, which will allow deletion of a particular code if there are several on an overlapped place.
But hte combobox and selecting a code, could bring that code to the front, so the entireity of the text coded with that code can be sen, and ther overlaps become hidden behind.

**Comment by glocalglocal** [comment]
The idea was (a) to reveal all (possibly more than 2 actually) overlapping codes that may otherwise be partially or completely hidden and (b) to allow the user to select one code for which all relevant codings anywhere in the text will be indicated (currently as underlined). 

Ideally, overlapping codings would show passively all the time, and vertical lines try to do precisely that, but any approach would have to work well with many codes/colours (more than 9) and several overlaps. I haven't seen yet a method that achieves all these things well.

**Comment by ccbogel** [comment]
I dont like the stripes idea. but I have another idea that may work. Check out the latest.
I have put overlining over overlapping codes in the text - so you can now see where overlaps are occurring.
Also - I added a combobox - so when you click on the overlapped coded text, the combobox is filled with each of the codes (as many as you have). When you double-click on a code in the combobox - the entire coded text for that code in that location will come to the front.

**Comment by glocalglocal** [comment]
Could a combination of single, double, dashed or other underline represent the three properties: overlap, coding/non-overlap, coding/overlap? Eg dashed for overlap, single for coding/non-overlap, double-underlined for both overlap and coding. I am asking because overlining takes some getting used to -- personally, I keep misinterpreting it but it may be me. 

Can the comboxbox entries show the codes colours?  

The double-click in combobox doesn't work here. 

Shouldn't '1 Overlapping codes...' be 'No overlapping codes...'? And '0 Overlapping codes...' should be 'No codes...'.

Not sure if this an issue in practice, but without a cursor you can easily lose your place -- that 'clicked position'.

**Comment by ccbogel** [comment]
OK i have changed this a bit. The overline works best for me, so  I will keep it to denote overlaps. you will get used to it Im sure.
Comobobox colours - have tried to implement - sort of works. Changed the way combobox works so a single click after selecting the code.
Cant have a cursor in the textedit as it is read only. Just have to remember roughly where you clicked.

**Comment by glocalglocal** [comment]
Is seeing the codings associated with a specific code now only possible by selecting the code in the tree? The combobox doesn't seem to have the functionality to show the dashed underlines. 

Tbh, overline is a pain but I persevere. I hope new users won't find it too awkward and move on.

**Comment by ccbogel** [comment]
I feel it would be much more difficult to have to try and implement the programming to have differing underlines for different things. i.e. overlaps and currently selected codes.
No the combobox does not have the underlining functionality when a code is selectd- but  I can add it back in if you feel it is needed.

**Comment by ccbogel** [comment]
ok the underlining functionality is there , and make the code selected in the combobox the current code.
I am very limited with different underlines in Qt. And I think the option of two styles might not be any better that the current system.
In any case, I feel this is better then the LHS code stripes used in other software.

**Comment by glocalglocal** [comment]
Yes, this method is better than the stripes. 
Thanks for the dashed underlines. I take it the combo can only show the colours in the open menu but not in the selected code when that menu is closed. At least a by-product of being able to select one of the overlapping codes is that you get the colour in the selected code above the tree.

**Comment by ccbogel** [comment]
yes thats right

**Comment by menelic** [comment]
I would like to reopen this issue simply because, in recent years, QualCoder has developed into a key solution for free and open qualitative analysis. Researchers are using QualCoder to conduct analysis and to free their past analyses from proprietary tools by exporting coding projects and importing them to QualCoder.

This, in my view, adds another key reason why the stripes mode of displaying overlapping code should be implemented in QualCoder—even if only as an option that can be activated or switched off. Regardless of individual preferences, the fact that key proprietary products offer this display option means that QualCoder can ensure a switch over with less friction and can ensure that past analyses remain more legible to researchers who are used to this paradigm. Please consider implementing this option to solidify QualCoder's status as a safe, open haven for qualitative analysis projects - those created in QualCoder and those imported to free analysis from proprietary walled gardens, unsustainable costs and in some cases, subscription pricing. 

Adding this will remove one more "argument" against QualCoder, reduce migration friction and further drive adoption.
