### ISSUE TITLE
alternative coders 

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#109]
I am not sure how having additional coders works. When I add a second one in Settings (another codename for myself) the first one disappears. 'Show other coders' in Codes is always greyed out. I can't see how I can tell qualcoder to show me the codings for another coder or switch to another coder, esp if I don't know there other codenames or which ones there are, saved in the data file (which is what created the problem with importing my RDQA project). One problem is that with older projects you may not even remember or can't easily find which codename you used (again, what happened with my RDQA project).

**Comment by ccbogel** [comment]
OK to add a new coder name - yes add it in the Settings dialog and click OK when closing the dialog.
You need to do something with this codername - eg code text, import file etc, otherwise the name will dissapear

One problem is that with older projects you may not even remember or can't easily find which codename you used (again, what happened with my RDQA project). - The other RQDA coder names will be in the drop down list, providing they have coded some text. Qualcoder defaults to the codername 'default' in new projects - this was the issue with the RQDA imports - but I have now fixed that.

To switch to another coder name, use the drop down list and select one from the list, (yes the first place in the list is empty) and click OK on exiting the dialog. This is the spot that shows you all the coder names.

In the code text dialog:  'Show other coders' in Codes is always greyed out - Yes -but I really should delete that, so that you cannot be aware of it.

**Comment by glocalglocal** [comment]
'This is the spot that shows you all the coder names.' -- When I imported from NVivo the coder name I used back then was not listed in qualcoder. I used a text editor to open the qda file to find the coder name. Unless I missed something, shouldn't qualcoder list somewhere (not the SQL dialogue) all coder names I specified and those that can be found in the text?

**Comment by ccbogel** [comment]
yes -this is one of those overlooked import issues I will have to address -as I did with rqda import.

**Comment by ccbogel** [comment]
coder name set when refi-qda project imported
