### ISSUE TITLE
'Text context' tickbox

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#110]
What does that do? It is in the codings report dialogue and ticking it doesn't seem to make a difference. It is not covered in the manual yet -- not even showing in the screenshots. Is it related to providing surrounding text for the contextualisation of the coded snippets? 

By the way, excellent manual. It really inspired confidence in the program.

**Comment by ccbogel** [comment]
Ah yes - I added this the other day - I should have hidden it from view. It does not do anything yet.
This will be a tick box so that when reports are generated, I can add in the extra text context around the coded text.
Or if unticked, then no extra text context.
This is the early stage of a feature you requested :)

Thanks re the manual, I guess I have a bit of skill in writing.

p.s. did you like the updated colour selector and the new way of unmarking overlapped coded text?

**Comment by ccbogel** [comment]
I have hidden this tick box for now

**Comment by glocalglocal** [comment]
The tick box is still there. 

The colour selectors is great. It could show somehow if a colour has been used already (just for info), but it's not worth the effort if it's not very easy -- something like adding emphasis to a colour tile. 

On context, in addition to showing surrounding text, clicking the filename in the report could also take you to the text in Code Text.

**Comment by ccbogel** [comment]
good point re the file opening
