### ISSUE TITLE
reports - text context

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#115]
Coded text in context.
On context, in addition to showing surrounding text, clicking the filename in the report could also take you to the text in Code Text.

**Comment by ccbogel** [comment]
In the results: clicking on the text shows the coded text in context of the original file

**Comment by glocalglocal** [comment]
I think it would make sense to scroll automatically to the point the actual highlight appears in the original text. 

Also, it is not obvious that you have to click on the highlighted code name. It also odd semantically because the highlighted coded name is the same for several snippets. Could there be a separate clickable element (icon, 'source', etc)?

**Comment by ccbogel** [comment]
I can add '[View file]' to the heading which might help direct the user.
