### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by VickySteeves** [ccbogel/QualCoder#12]
Hello! I'm Vicky Steeves, a librarian. I stumbled across this repo today and just wanted to say hi and mention some fellow FLOSS qualitative software out there! The current options for qualitative are so locked down and I am so happy that there are folks working in this space :smile_cat: 

- I work on [Taguette](https://gitlab.com/remram44/taguette/) with @remram44, an open source qualitative software that works self-hosted on a server and desktops (all OS). More info on [our site](https://taguette.org) too.

- @bduckles works on [qcoder](https://github.com/ropenscilabs/qcoder), an open source R library for qualitative analysis. More info in their [motivation document](https://github.com/ropenscilabs/qcoder/blob/master/motivation.Rmd). 

Anyway, I'm sorry if an issue isn't the best way to introduce myself and the efforts in this space, but I hope we can chat at the very least and encourage more openness in qual!

**Comment by ccbogel** [comment]
Hello Vicky, good to meet you, and thanks for having a look at my repo. You have a flashy website for Taguette. I will have a closer look and give it a test drive later when  I have more time. 
Yes it is good that between us all there is more capability and potential for free, open source software in this area. Yes I did look at the repo for qcoder but did not try it out.
The main software used at my uni is Nvivo. It is quite expensive and I think a bit overwhelming with options. My project developed out of my PhD in which I originally used RQDA.
I was encouraged by WPFilmaker (Github) to add audio video coding ability, which I believe I have managed to get working OK.

**Comment by WPFilmmaker** [comment]
Hello Vicky! I am write here despite being a simple users because I would like to remark that visibility plays a big role for niche projects. I had never heard of Taguette Despite extensively looking for FLOSS qualitative analysis projects :/. That's why I suggested @ccbogel to make installation easier and spread around that QualCoder exist :D By the way asap I can fix my vm I will try all the new features you implemented!

And I agree with the statement that "It's not right or fair that qualitative researchers without massive research funds cannot afford the basic software to do their research" found on taguette website!

**Comment by VickySteeves** [comment]
@WPFilmmaker Taguette started up September 2018 so it makes sense that you might have not found it! It's a somewhat new project. It was recently added to the [Wikipedia CAQDAS](https://en.wikipedia.org/wiki/Computer-assisted_qualitative_data_analysis_software) article -- like QualCoder :smile_cat: 

@ccbogel oh wow! I tried to use RQDA so many times and could never get it to work, so kudos to you for that! Also, A/V capability is awesome! And I think that is quite hard to do, so double kudos!

@bduckles and I are presenting at [csv,conf](https://csvconf.com/) about open qualitative software so hopefully we'll get the word out to some folks there about the 3 options they have now :1st_place_medal: which is so exciting!

Anyway, let's stay in touch and see what we can do about supporting each other's approaches to open qual software! The next thing that we want to do for Taguette is to adopt this open standard for exporting/importing qualitative analysis projects -- this would make it easier to go between software, and even NVivo and Atlas.TI have adopted it! Details are here: https://www.qdasoftware.org/downloads-project-exchange/ && https://www.qdasoftware.org/codebook-exchange/

**Comment by ccbogel** [comment]
Great to hear from you Vicky. Yes I did get RQDA working, and then at one stage it didn't, which initially spurred development of the earlier version of this software, and now the later version. Yes A/V was challenging to find something that worked in the frameworks that I have used, and is still probably not perfect, I was thinking there is probably a need to add a scaling factor for really long vids. But that would seriously be for a much later time.
Thanks for the open standard links - as if I don't have enough time now to implement changes...
The conference looks good, I presume Portland in the Spring is wonderful.

**Comment by WPFilmmaker** [comment]
+1 for the support to open standards...FLOSS software are usually disadvantaged against their proprietary 'competitors' therefore compatibility it is almost mandatory, otherwise people won't be able to switch (e.g Libreoffice supports Ms Office formats, GIMP supports Photoshop formats etc.). Since it is an open standard and also used by NVivo and Atlas it seems a very good idea and hopefully ccbogel will be able to implement it .

**Comment by ccbogel** [comment]
I have begun looking at the Codebook exchange. There appear to be discrepancies in the codebook.xsd:
https://www.qdasoftware.org/wp-content/uploads/2019/03/Codebook-mrt2019.xsd
and the documentation:
https://www.qdasoftware.org/wp-content/uploads/2019/04/QDAS-XML-1-1.pdf

In the xsd Description is an element, but in the example Appendix A it is an Attribute.

**Comment by WPFilmmaker** [comment]
@ccbogel any news on this? Have you been able to deal with the discrepancies?

**Comment by ccbogel** [comment]
Hi @WPFilmmaker. I have not done further work with the codebook. However , I have attempted implementing the Project Exchange export. In this I have also emailed someone from the REFI group for assistance with exporting variables. I believe qualcoder can currently export text, images, a/v, codes, code selections and some notes. I cannot test whether this is correct though as I don't have a program to trial importation. I also have not made an updated deb file, as I think this capacity needs further work still.

**Comment by WPFilmmaker** [comment]
@ccbogel, Hi! Thanks for the reply! Do you have any links for the Project Exchange? I tried googling but it does not come up :/

By the way I managed to restore my virtual machine so now I  am able to provide testing for Ubuntu 18.04 again.

**Comment by ccbogel** [comment]
The links are here from @VickySteeves  Details are here: https://www.qdasoftware.org/downloads-project-exchange/ && https://www.qdasoftware.org/codebook-exchange/
Great that Ubuntu is up and running.

**Comment by WPFilmmaker** [comment]
@ccbogel thanks!
Is there anything you need more testing with? I will be happy to help out since I have some free time now.

**Comment by ccbogel** [comment]
HI @WPFilmmaker, I guess general usability and reporting would be good. I am not planning to do text-mining for a long time.
I havent been much involved lately due to work commitments. I did send my versions of project exchange and codebook exchange to Janine Evans (KWALON project exchange, but have not received any feedback E: kwalon@eversresearch.nl URL: www.kwalon.nl). 
I am hoping to get some project exchange format files from another commercial qualiative software, and will try and load it into QualCoder over the next month or two.
