### ISSUE TITLE
Code freqs export

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#184]
Code freqs / Export: I get a text file but my text editor complains 'some number of solitary carriage returns were detected and removed'. Then the file opens OK. 

Would it be useful to make the file csv or otherwise importable? 

All caps in the filename is not nice. Should the filename refer to the project name, possibly with a date/time stamp to avoid clashes? 

EDIT: The Code Freqs window size is not remembered.

**Comment by jdittrich** [comment]
Hi @glocalglocal it would probably make sense to split this up into several issues (except @ccbogel prefers otherwise)

If I read it right it is:

* Text editor complains about exported file (Also relevant: Which editor complains and does it also happen with other editors?)
* Suggestion: Standard format for code frequency exports like csv (would probably be only worth doing if you and/or other people have a clear need for this)
* Filename in code frequency export should not be caps and refer to the project name
* The Code Freqs window size is not remembered.

**Comment by ccbogel** [comment]
@jdittrich thanks. Yes a separate issue for each problem or request is preferred. As i can resolve one thing and remove the issue. Rather than implement some of several, and then decide to close or leave open an issue.

**Comment by glocalglocal** [comment]
It's just that I have been reporting or suggesting so many things, while quite often many of them overlap or are linked, I feel separate issues would complicate things and add an overhead. I will try though.

**Comment by ccbogel** [comment]
@glocalglocal  OK thanks - it becomes hard for me to follow otherwise.

**Comment by ccbogel** [comment]
Code frequencies export should be correct now. please try it.
The other fixes for the report have been implemented.

**Comment by glocalglocal** [comment]
Exported text file opens OK in metapad as well now. The other issues above (now submitted as separate issues) remain.
