### ISSUE TITLE
Qualcoder crashesh on startup

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#2]
Hi,
I installed pyqt5 with `sudo apt-get install python3-pyqt5`, as `sudo pip3 install pyqt5` was not found.

I ran the installer and I can see Qualcoder icon so everything went fine (I think).

When I try to run Qualcoder a black window appears for a seconds and after blinking it closes.

I tried to run in terminal `python3 qualcoder.py` (from Qualcoder-master folder) but I get a no such file or directory.

How can I try to run it from terminal and provide to you more info about the crash?

I am on Lubuntu 18.04.

**Comment by ccbogel** [comment]
Hi there,
thanks for finding and trying out the software that  I made.
I am sorry that you had some difficulties setting it up, so  I will suggest some options below:

Thanks for the update regards install python3-pyqt5 - I guess different distros need different code to get pyqt5 installed.

Check that pyqt5 was installed by doing the following:
Open terminal and type: python3
This will open the python3 interpreter inside the terminal
Then type: from PyQt5 import *
If the above command does not show any errors - then PyQt5 has been installed.
To get out of the python interpreter - type ctrl + d

To run it from the terminal:
You need to move into the main code folder before you run: python3 qualcoder.py
Inside the QualCoder-master folder is another folder called QualCoder - this folder contains all the python code.
This is where you need to be to to run: python3 qualcoder.py

Running from terminal would be good - because you can see any errors.
Also in your home directory there should be a qualcoder.log file - this will hopefully log any errors as well.

One other thing I thought of:
Make sure the qualcoder.py file is executable
So for me on Linux Mint - I tick the executable box when I right-click on properties for the qualcoder.py file  (example in the attached picture)

So try these above things first.
Also you could also make the qualcoder.py file executable in this directory:
/usr/share/QualCoder
try: sudo chmod 777 /usr/share/QualCoder/qualcoder.py

I hope this helps,
with regards Colin

________________________________

**Comment by WPFilmmaker** [comment]
Thank you for your prompt reply Colin!

I was able to fix the issue simply by running QualCoder from the right folder as you said.

I am a real beginner in qualitative analysis (I learned a bit of quantitative though) but I think it could be useful in the future so why not :) I am quite busy these days but I will definitively test QualCoder and report feedbacks/bugs from an user pov.

I am now following the 'how to' from your website. I was able to import the example files, however when I try to import ID1.docx I get the following error:

Traceback (most recent call last):
  File "/home/lubuntu/Downloads/QualCoder-master/QualCoder/manage_files.py", line 336, in import_files
    self.load_file_text(f)
 
  File "/home/lubuntu/Downloads/QualCoder-master/QualCoder/manage_files.py", line 384, in load_file_text
    document = opendocx(import_file)
 
  File "/home/lubuntu/Downloads/QualCoder-master/QualCoder/docx.py", line 106, in opendocx
    document = etree.fromstring(xmlcontent)
 
AttributeError: module 'xml.etree' has no attribute 'fromstring'

Any idea how can I fix this?
Best Regards

**Comment by ccbogel** [comment]
Hi again, yes testing code in different distros is really good.
Some linuxes use xml and some use lxml  - I have been using lxml in the docx importer
I have added to the How to instructions page on this too.

OK you need to install another module:
sudo apt-get install python3-lxml

Then hopefully this will work ok.
its good to see that the program appears to be working OK otherwise for you.

regards Colin

________________________________

**Comment by WPFilmmaker** [comment]
Hello Colin,
I followed your suggestions and it works perfectly!
Best Regards
