### ISSUE TITLE
UI source code?

### ISSUE THREAD

**Issue by bennettscience** [ccbogel/QualCoder#27]
I wanted to try and add in some keybindings to speed up code entry, but the `.ui` source files are missing from the repo and all of the `GUI/*.py` files warn of losing modifications. Are you planning on including the source documents into the repo at some point?

**Comment by ccbogel** [comment]
I have uploaded the ui files. I guess you have used QtDesigner before. I will make some changes to widget sizes over time. This is mainly because another user, @qwertygc, is helping to translate into French. I also have some German language skill too, So after doing some translations and seeing how the wording fits into labels and buttons, etc. it will necessitate some resizing.

**Comment by bennettscience** [comment]
I haven't used QtDesigner before. Most of the Python apps I've built have been web based using Flask rather than desktop apps. But, I learn quickly :-)

I've set up my remote to track this repo as well, so I'll get all those updates as I tinker. Thanks.

**Comment by ccbogel** [comment]
Make use of QtDesigner, its easy. You can add an ampersand '&' as the start of a letter or menu option . Then alt+letter moves you to that section or opens a menu option.
I have found in another project that it does not always work well though.  
I haven't used Flask before, but one day I will experiment.
