### ISSUE TITLE
Usability: Make it possible to change start and end position of codes via drag and drop

### ISSUE THREAD

**Issue by menelic** [ccbogel/QualCoder#273]
While the right click menu option to change start and end position for codes is helpful its hit and miss if the start or end point needs to be changed by more than a few letters. It would be better if drag and drop handles appeared at the beginning and at the end of the code that can then be positioned. I do understand that it should not be possible to trigger such an option too easily (eg by double clicking on a code) which is why I think keeping it in the right click menu and enhancing it is a better solution.

**Comment by ccbogel** [comment]
@menelic OK I have added keystrokes for this rather than handles on a code - which would be very hard to implement.
Process: 
when in the textedit, click on a code with the mouse (Note the code must not be overlapping with another code at that position).

Shift + left arrow            Extends coded text to the left
Shift + right arrow          Extends coded text to the right
Alt + left arrow               Shrinks coded text from the right hand side towards the left
Alt + right arrow            Shrinks coded text from the left hand side towards the right

I have only implemented this in the Text coding for now. If its works well, then I will add it to the video - text coding.

**Comment by menelic** [comment]
@ccbogel this works very well, thanks a lot once again for taking this up so swiftly and for implementing such a helpful enhancement. I suggest you make this functionality available via right click as well and replace the old "change start position" option as it is less intuitive. But even if you prefer to retain the old "Change start position" menue alongside this new option, I strongly suggest that you release 2.1 with this and many other enhancements that are in the master now.

**Comment by ccbogel** [comment]
@menelic Thank you. I cannot make this functionality available via the right click menu. But I have detailed the process in the manual. If you think it best, I can remove the 'change start position' menu options, or as they work, just leave them in.

Also look at some other issues I have addressed: eg the getCodingTable and the Relation function

I will close this issue soon.
