### ISSUE TITLE
MAXQDA REFI-QDA project export files

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#281]
@menelic Hello. I wonder if you would be able to provide me with 1 or 2 REFI-QDA project files.

I need one that contains an image (jpg or png) and some coding done on the image.
I need one with a short video (mp4) and some coding done on that.

I would like to test the import of these files and check that the import with codings works well.

**Comment by menelic** [comment]
@ccbogel A team member produced a REFI Export from MaxQDA with codings on an image and a video, Please let me know if you need another file with codings done just on a video or just an image to enable separate testing.  We hope this is helpful for you to advance the important work of making QualCoder a safe harbour for codings and analysis done in proprietary software. I believe this would provide a major boost for QualCoder and make it possible to allocate institutional resources that are currently spend on licensing fees to the development of QualCoder. 

Please note - the file is not zipped, just renamed - so just remove .zip from the fle name to obtain the original REFI file. This was done due to GitHub restrictions on uploadable file types.

[test_synthetic_survey_small.qdpx.zip](https://github.com/ccbogel/QualCoder/files/5522853/test_synthetic_survey_small.qdpx.zip)

**Comment by WPFilmmaker** [comment]
@ccbogel I know a colleague who might be able to provide a test file with the specs you asked. No idea what software version they use, but if you need, I can ask for a file.

**Comment by ccbogel** [comment]
@menelic Thank you. Ooop this has thousands of files again. But that is OK I will wait for the import and then the manage files dialog to add all the placeholder to the attributes (this is a slow process).
So far  its good:
![pic1](https://user-images.githubusercontent.com/5834638/98868704-ab3ca380-24c4-11eb-8aab-9b18fc85e708.png)
The coding window for images looks good (The coded areas contain memos like this: (109,91),(337,243) - is this the correct text and matches what you did?
![pic2](https://user-images.githubusercontent.com/5834638/98869114-5cdbd480-24c5-11eb-8f2a-eb9ecfbd033d.png)
I could load and play the Hahn video - I did not see any codings in here - so  I will investigate.
In the Mange Files - View - to view the video - QualCoder struggles - as there are thousands of files in this project. As after it opens the viewing dialog it refills the table - so I have made a change to stop this issue.

**Comment by ccbogel** [comment]
@menelic Thank you. QualCoder can now successfully import the video, picture, the coded sections are loaded. The variables are loaded.
One final thing would be to had a 'transcript ' for the video - a couple of lines even, with a coded word.
