### ISSUE TITLE
QualCoder 2.2 does not show file type icons

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#350]
This was an issue I always encountered since you implemented the icons, I never reported it as I thought it was maybe just my version which was old. However after updating to 2.2 I still don't see the file type icons: https://imgur.com/a/xZPGOf5

I am on Lubuntu 18.04 QualCoder 2.2.

**Comment by ccbogel** [comment]
I am at a complete loss why they do not display. It will be interesting to see of all the icons display when a 2.3 version is released. You could test the latest code (download using the green code button). Use the terminal to then start qualcoder by moving to the directory containing qualcoder.py and typing python3 qualcoder.py
The reason I ask you do this is because the way the majority of icons are displayed is using one approach, but in the next release (and the latest code) I will be using a different approach that loads icons in the same way as the missing file icons that you are having trouble with.

**Comment by WPFilmmaker** [comment]
@ccbogel I tried as you said, here is the results:

Icons show: https://imgur.com/a/XfYSX7D
Buttons works fine: https://imgur.com/a/WZFWAcD

Whatever you changed it worked :D 

ps: nice colors!
ps2: in the second screenshot you can see that some text gets cut, can you do something about it?

**Comment by ccbogel** [comment]
You must be using a large font size.  I can make the rectangle slightly taller.

**Comment by ccbogel** [comment]
OK i have updated this, so will close this issue for now
