### ISSUE TITLE
When a window is open in 'code text', it is impossible to interact with other parts of QualCoder

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#351]
How to reproduce:

Go on code text
perform any action to open a window (for example change color)
a new windows open 
if you try to click outside the window the mouse doesn't work
If you try to minimize the window you open you still get your mouse not working, the only way is to close the window.

IMHO this shouldn't happen. For example if I have the change color window open I would like to scroll the codes to check what color I am already using but it is not possible.

I am on Lubuntu 18.04, Qualcoder version master downloaded a few days ago.

**Comment by ccbogel** [comment]
This is a modal dialog, so I cannot do what you are asking. That means you have to interact and close the window before doing other actions.
I can add a mark to each colour box to note that is is being used for a code. And maybe a tooltip to indicate which codes.

**Comment by ccbogel** [comment]
I have enacted my above changes.

**Comment by glocalglocal** [comment]
I think the code should be stated in the dialogue (eg on the title bar, as in 'Colour selector for code1). 

And the whole thing could be made simpler and more intuitive. Old and New at the top could be removed. '*' or (better) 'used' would indicated Used, 'Current' or 'Old' (instead of '*') in the actual palette colour would indicate Current, 'New' would indicate New if another colour is selected. You don't even need to explain anything.

**Comment by ccbogel** [comment]
Improved. I wont implement the use of words such as current etc.
When I hover over the colour, only one of the codes is listed. one or more codes will be listed - but this wont a colour you have immediately selected in this dialog.
Incidentally, can I still assign the same colour to multiple codes? Yes

**Comment by glocalglocal** [comment]
I have two codes sharing the same colour. The tooltip still shows the 
first one only.
