### ISSUE TITLE
Req: Add compatibility with TXM and Iramuteq?

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#358]
The open source software TXM and Iramuteq are used to quantitatively analyse a corpus of text (lexicometric).  They are thus, in my opinion, complementary to Qualcoder which has a qualitative approach.

To communicate, they use a particular file format called "Iramuteq": http://www.iramuteq.org/documentation/formatage-des-corpus-texte The source code of Iramuteq is free and in python: http://www.iramuteq.org/git?p=iramuteq;a=tree

I don't know to what extent it might be interesting to provide compatibility between these different softwares.

**Comment by ccbogel** [comment]
I think this may be quite difficult, and not a priority for now. 
I am still slowly working on REFI-QDA project import/export also.

**Comment by WPFilmmaker** [comment]
@qwertygc Iramuteq seems cool and uses R but it seems it is in French only right?

About quantitative analysis, khcoder https://github.com/ko-ichi-h/khcoder, is another popular software (it seems particularly famous in Japan but its long list of publications where it has been used include many non-Japanese scholars too), it works on Windows and linux too (but its installation is quite tricky), it used to work under WINE but not atm... Don't remember what format is uses though, when I managed to get it run I will update my message. 

Software interaction, especially among FLOSS projects, is good, of course there are limitations to what can be done.

**Comment by AndrzejWawa** [comment]
Hi, 

It seems to me that complementary use of the QC and Iramuteq/Khcoder is already possible, without additional actions (let me know if I am wrong of course).

You can upload the same plain text files from QC project folder to the quantitative softwares and run analyses (by the way, it may be advantage of plain texts, that many other softwares use them). Moreover, QC has quite good exporation functions, so you can also extract fragments coded by specific codes and (after eventually preparation in Calc) also upload to statistical softwares.

However, there could be need for conducting qualitative and quantitative analysis at the same time, and then, synchronizing all softwares could be helpful. However, I think that it is justified to check, before implementation of this, if there are users who really need this. Perhaps, adding to QC some additional functions (Colin already wrote somwhere about this), like e.g.

a) specific words counting, after selecting files, cases, codes, categories ect.
b) words cloud etc.

But I am not sure if it is urgent, because, maybe if someone want to conduct deeper qunatitative analysis of text, better for her is directly going to advanced quantitative corpus analysis software. If someone want to use previously coded extracts, there is exporation option in QC.

So, decisive for me is question, whether someone aready needs such a synchronization.

**Comment by qwertygc** [comment]
Yes, indeed, I see interaction between FLOSS Software for not to reinvent the wheel.

**Comment by ccbogel** [comment]
This is a feature that I dont intend to implement.

**Comment by qwertygc** [comment]
No problem. The R package [Rainette](https://juba.github.io/rainette/index.html) use the same method and we can imagine an other system.
