### ISSUE TITLE
REFI standard

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#37]
Rotterdam Exchange Format Initiative (REFI) open standard for exporting/importing qualitative analysis codebooks and projects.

[https://www.qdasoftware.org/downloads-project-exchange/ ](https://www.qdasoftware.org/downloads-project-exchange/ )
[https://www.qdasoftware.org/codebook-exchange/](https://www.qdasoftware.org/codebook-exchange/)

Currently: QualCoder can export a codebook. The codebook was successfully imported into NVivo.
I am in the process of developing the project export - but there is still a lot more work to do on this.
Currently QualCoder cannot import codebooks or projects.

**Comment by ccbogel** [comment]
I have been able to import a codebook.qdc in the REFI-QDA standard from Nvivo. The QualCoder code has been updated for this. Probably needs testing with other QDA software too, if anyone has access and ability to test.

**Comment by ccbogel** [comment]
REFI codebook import and export
These appear to work well and appear to comply with the REFI standard.

REFI project import and export
Exports
Coding for a/v transcripts is also exported as a <TextSource>.
Transcript syncronisation with a/v is approximated from textual timepoints in the transcript. Large > 2GBfiles are not stored externally.

Imports
Text coding positions do not match up. This was experimented with using Nvivo project export and then imported into Qualcoder. I cannot find a way to resolve this issue at the moment. Sets, or collections of audio/video/text/images are not imported into Qualcoder. Qualcoder does not use this functionality. Node graphs are not imported into Qualcoder, as Qualcoder does not have this functionality. Large > 2GBfiles are not stored externally.

Qualcoder REFI project exchange is not yet compliant with the exchange standard.

**Comment by ccbogel** [comment]
Thanks for your support. REFI compliance is hard to achieve. Work on this will be slow.

**Comment by menelic** [comment]
To aid the implementation of REFI import in QualCoder (even if limited to text import would make QualCoder a Safe Haven from vendor lock-in and the go-to choice for teaching coding) we have created a REFI export file with widely used MAXQDA qualitative coding software. 

[test_synthetic_survey_small_MAXQDA.zip](https://github.com/ccbogel/QualCoder/files/5388224/test_synthetic_survey_small_MAXQDA.zip)

coded from this source file:
[test_synthetic_survey_small.xlsx](https://github.com/ccbogel/QualCoder/files/5388233/test_synthetic_survey_small.xlsx)

When importing this file into QualCoder, the code tree is correctly imported but the coded text is missing, no file can be selected from the view file menue and changing the coder in settings does not give access to the codes. It seems the import is almost there, here is hoping that text import would be on the cards. Due to an error in earlier versions of QualCoder we are using MAXQDA for a project and it would be great to migrate to the current, more stable QualCoder. 

Please note that in MAXQDA, a category can be a code at the same time. In this example file, "Friends and Family" is such a "Code-Category" while "Interests" is just a category. QualCoder, which dos not ofer "code-categories" correctly imports "Friends and family" as a category. 

Due to errors with an earlier version of QualCoder we did some coding in MAXQDA that we would now like to "rescue" back into the recent QualCoder version where the error has been solved #265 . I am sure many others would gladly free their analysis from proprietary vendor lock-in as well.

**Comment by ccbogel** [comment]
@menelic Thank you again. Having a test case such as a MAXQDA REFI-QDA file is _really_ useful. As the www.qdasoftware.org site does not have sample qdpx files for testing from different vendors. 

Qualcoder does not have a _category as code_ option. It was never set up like this. I will see if I can work with around this in some way.

For personal interest: Despite the error that occurred for you, to use MAXQDA, why do you then prefer QualCoder?

**Comment by ccbogel** [comment]
@menelic I have uploaded an updated refi.py file
This addresses an error I found with variable memos and also the folder than contains all the files. It now checks for 'Sources' or 'sources' as the folder name for where the files are stored. This was a big error solved.

I never expected QualCoder to be used for thousands of files. So yes the import is slow, and yes, opening the Files window can be slow. On first opening this window, It checks and adds placeholder for values for variables, so doing this for thousands of files is also slow.

TODO: category as code from MAXQDA.

**Comment by ccbogel** [comment]
@menelic I have uploaded another update. Now when importing the MAXQDA qdpx file QualCoder looks for a codable category. When found it also creates a code with the same name. Shown in picture below:
![pic1](https://user-images.githubusercontent.com/5834638/96220289-30bb5980-0fd4-11eb-996f-43851efa6d3f.png)

**Comment by ccbogel** [comment]
@menelic 
"The only issue is that in the above example, the data structure is that of a survey imported into MaxQDA for coding. When a survey is imported to QualCoder, the interface shows all IDs that are followed by codeable text. But after importing of the MaxQDA REFI QualCoder shows only one ID and code at a time. I am aware that this has to do with the underlying data structure (each row a file) but I am sure it must be possible to have this displayed like a survey imported into QualCoder for coding"

This is the parsing of the qdpx file:
Parse users. Loaded: 1
Parse codes and categories. Loaded: 11
Parse file variables. Loaded: 2
Parse case variables. Loaded: 0
Parsing sources. Loaded: 6419

Each text source from MAXQDA was put into a separate file. It will be very difficult to recreate one text file from all of these separate one and keep the coding correct.

**Comment by ccbogel** [comment]
**TODOs for project import and export.**
Currently working on the 2Gb linked files for import and export, with relative and absolute paths.

_TODO load_audio_source - check: load transcript, transcript synchpoints, transcript codings
TODO load_video_source - check: load transcript, transcript synchpoints, transcript codings
TODO - test of import and export with other QDA software._

**Comment by ccbogel** [comment]
Thanks to @AndrzejWawa who early January tested import from QualCoder into Quirkos, MAXQDA and Atlas.ti. The summarised reports is attached.
One of the main differences is the way groups/sets/cases is organised in different software. In the future, I might make Cases and Case attributes export also as Sets in REFI-QDFA Project Export.

[REFI-QDA Project Import Quirkos Maxqda Atlas.pdf](https://github.com/ccbogel/QualCoder/files/6016451/REFI-QDA.Project.Import.Quirkos.Maxqda.Atlas.pdf)
