### ISSUE TITLE
Recurring error

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#384]
Hi,

During every second opening of QC I have such the error. Do you know that is it?

![image](https://user-images.githubusercontent.com/77200214/107551097-20a63600-6bd2-11eb-863e-82fb125661b6.png)

**Comment by ccbogel** [comment]
@AndrzejWawa Hello, I have not had this occur to me. I did not change any code in the backup from 2.2 to 2.4.
I suspect (but am not certain)it could be due to the very long path and file name. More than 255 characters which is a problem in older Windows and has a workaround in Windows 10. It will not affect the text stored in the qualcoder sqlite database, it is just struggling to copy the original text file. 
Solutions: 
1 As the text file is not used, it is only a stored copy for reference, you could shorten the file name. Open the qualcoder project folder/documents and rename. (Add a memo to remind yourself of the change).
2 Remove the original text file and make it a linked file - for within QualCoder
3. Remove the text file and store it some where else, but do not link. As QualCoder will not refer to the original text file again (unless creating a REFI-QDA Project export), it will use only the database stored text for coding.
4 Do not have QualCoder do automatic backups, but do them manually yourself, when you need to. - Actually curious to see if a similar error would occur.

**Comment by AndrzejWawa** [comment]
Thanks! It works properly when shortened the names. 

Indeed, I have this problem with too long names in general when coping files.
