### ISSUE TITLE
Unnecessary information window

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#420]
Hi,

When I am using the shortcut "q" to code, the window with informaiton that the text was already coded appears. However, it also appears when I code previously uncoded text.

When I am using shortcuts to change start and end position it is changing by 3 characters at one time. However, I do not know if it is a bug or your intentional change.

**Comment by ccbogel** [comment]
When I am using shortcuts to change start and end position it is changing by 3 characters at one time. However, I do not know if it is a bug or your intentional change. 
This is a bug that I cannot fix, unfortunately. When you press the shortcut keys, it triggers the event to occur, depending on the computer speed or program slowness, it can fire multiple times. You can right click on the coded text and using the menu, change the start and end positions of the coded section.

**Comment by ccbogel** [comment]
When I am using the shortcut "q" to code, the window with information that the text was already coded appears. However, it also appears when I code previously uncoded text.
Yes another bug. The event that occurs when pressing q is firing multiple times (similar to the above issue with changing start/end positions).
I have hidden the warning now.
