### ISSUE TITLE
Bug: Font size in coding report

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#433]
Shouldn't the font size in the main text box in Coding Report be determined by the font size in Settings, or a local dialogue setting (like in Coding)?

BTW, not sure why Coding has a local font size setting that is different from the one for all docs in Settings. I suppose the more choice, the better.

**Comment by ccbogel** [comment]
In coding reports:
yes it uses the General font size. Do you want this to draw from the Documents font size?

RE the font options in the coding text pane - yes a historical quirk,  I can remove that.

**Comment by glocalglocal** [comment]
I think all document-length displays should use the Documents font size. Reading a tooltip in small-ish font is fine. Reading 5000 words is different.  

> RE the font options in the coding text pane - yes a historical quirk, I can remove that.

good for consistency and it will save some space on the toolbar.

**Comment by AndrzejWawa** [comment]
I think that the possibility of changing the font size directly in the coding mode is good. Taking into acount, that the most amount of time we are spending during coding, as well as we can change our position (from the desk to sofa ect.), we could also change the size of coding document more often than others.

Moreover, it make a good impression for newcomers, because it immediately presents the flexibility of software.

When it comes to space on the toolbar, it is big anyway, why you have possibility to hide the whole toolbar by "h".

And I think it is consistent, you have default size for documents in settings, the QC always will open documents in this size after running the software, however, during the work, you can immediately modify this size to you current needs.

So, I opt for preserving status quo when it comes to local possibility of changing size in coding mode : )

**Comment by AndrzejWawa** [comment]
However, when coursor is on the local changing size in coding mode, there could be an information that the permanent default size for documents is possible in the setting - to avoid confusion, why text size in coding document always is the same after reopening.

**Comment by ccbogel** [comment]
OK closing this now. its been updated in Reports
