### ISSUE TITLE
Bug: non-overlapping parts of overlapping codings

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#443]
Overlapping currently refers to a specific point in the text. It should instead refer to the whole coded fragment. So, when two codings overlap partially, if you click where, say, only code1 applies, QC reports no overlap. This means that I can't ask QC to show coding1 in its entirety, even though it may be partially covered by coding2, unless I point to the area of overlap which is not always obvious with multiple codes.

eg if C is on top of B which is on top of A below:
AAAAAAAAAAAAAAAAAAABBBBBBBBCCCCCCCCCCC 

and you click on an A, QC will claim there is no overlap and won't let you bring the whole of As string to the foreground.

**Comment by AndrzejWawa** [comment]
But I think that this improvement should only be introduced for the purposes of showing codng in the coding mode. However, should not impact the rules of creating "Code relations" reports for example, because there, it is meaningful if the codes overlap strongly or weakly.

**Comment by glocalglocal** [comment]
I agree. The point is to improve management and visibility of complex codings in Coding.

**Comment by ccbogel** [comment]
I have made it so that as well as the overline, the overlapping section is italicised. 
Italics also is applied to a coded section where there is a memo added to that coded section.
I think this is ok as the italics will draw attention for mouse hover to identify both a memo and/or  overlaps.
I have a default in that shorter codings are shown last (on top), when a file is loaded, so the overlaps are more visible.
The non-overlap should not visually appear as an overlap, in my opinion.
Using O or the combination box above right, then cycles through.

**Comment by glocalglocal** [comment]
In the ABC example above there is no way to even suspect the A block is as long as it is unless you specifically check the B and C sections. And this is just a simplified example here :) But in complex scenarios there is no perfect way to resolve this I am afraid.
