### ISSUE TITLE
Double annotation window

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#485]
When I open annotations by "a" shortcut, and then close it, it reopens once automitacally. 

UPDATE: the problem is that using the shorcut you creates two annotations at the same time. Then, it influences the SQL tables (double rows). This is not the case when regarding context menu creation of annotations which works properly.

**Comment by ccbogel** [comment]
I have fixed the cause of this now. My coding error. I had inserts instead of updates.
There is not a super easy fix to removing doubled up annotations.

I suggest you run the sql to identify those that are doubled:
select * from annotation order by memo. Check is is the same pos0, pos1 and fid and coder name.

Then if you make a note of the anid  for each that you want to delete:
An example:
delete from annotation where anid in (1,2,3,4)

Before deleting anything, make a backup of your project.

**Comment by AndrzejWawa** [comment]
Thanks! No, I did not have many annotations, actually only two, so deleted them manually : )

**Comment by AndrzejWawa** [comment]
It works properly, however, after clicking "ok" (when you previously opened annotation by "a"), window automatically reopens second tme. However, it does not cause double annotations now.
