### ISSUE TITLE
Bug: 'Important' doesn't change text to bold

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#523]
I apply two codes to a sentence. I set the first one as 'Important', it registers OK, but the text is not displayed in bold. 'Important' works as expected (ie text changed to bold) only with the second (final?) code.

**Comment by ccbogel** [comment]
A difficult issue to fully fix as it depends on which code is 'on top'. I have made it so that if the exact same text is coded with 2 codes, the 'important' one is displayed on top. However if you mark the first code as important then assign a second code to the same text, it will not be immediately visible, although it will be italicised and show when the mouse hovers over.

**Comment by glocalglocal** [comment]
If I use the drop-down menu to select a different coding to go on top and then back to the one that is set as important, bold doesn't come back. It does if I switch to another text and back.
