### ISSUE TITLE
Transcription window not opening 

### ISSUE THREAD

**Issue by DaniloCarlosRomero** [ccbogel/QualCoder#618]
1. Suddenly I could not access the transcription window (it does not pop up) , using qualcoder 2.8..exe 
I've updated python and vlc and also try to solve the issue by running Qualcoder 2.9, with no improvement. 

Error message: 
**[00000258b411e040] mmdevice audio output error: cannot initialize COM (error 0x80010106)**

2. I do not know if this issue is connected, but when I try to delete the mp3.file the following error message pop up: 

Error message: 
**ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
Traceback (most recent call last):
  File "qualcoder\manage_files.py", line 1490, in delete_button_multiple_files**

![not possible to delete file](https://user-images.githubusercontent.com/61665339/155125263-7dc642d5-7ee5-4111-8942-bb8e169a90c7.png)

**Desktop**
 - OS: Windows 11

Please let me know if you have any suggestions about how to fix this issue.
Best, 
Danilo

**Comment by ccbogel** [comment]
@DaniloCarlosRomero 
1. This error:  [00000258b411e040] mmdevice audio output error: cannot initialize COM (error 0x80010106) has something to do with the python bindings to VLC. 
Is this error actually stopping the playback of the mp3, or is is just displayed in the black command box, and can be ignored?

2. Yes that is a programming error that is fixed in the latest code. If you are running 2.9. Please see the instructions at the bottom of the 2.9 releases page to fix (Under heading One Issue identified in this release).
https://github.com/ccbogel/QualCoder/releases/tag/2.9

**Comment by DaniloCarlosRomero** [comment]
@ccbogel 
1. This error is displayed in the command box. I cannot access the (transcription) window where the playback features are available. The transcription window (with access to playback features) shows up as a blank window.  
![IMG_2371](https://user-images.githubusercontent.com/61665339/155365386-01537f68-0fe4-4429-8608-224aa89aaf5d.jpg)
2.  Thanks! 
3-4. Yeah, deleted the .txt to try again with other files. Been using Qualcoder for a year now, it has been working fine until now. My first guess was that it had something to do with updates in the dependencies. Been installing and re-installing python, vlc and qualcoder for several times without being able to access the transcription window. Do know you if someone has experienced the same issue?

**Comment by ccbogel** [comment]
no one else so far has this problem

**Comment by ccbogel** [comment]
There has been no further feedback on this. Will close the issue in 1 week.

**Comment by ccbogel** [comment]
Closed - unresolved - no feedback from Danilo
