### ISSUE TITLE
Alternative Windows Installation not Working

### ISSUE THREAD

**Issue by agsolbe2** [ccbogel/QualCoder#620]
**Describe the bug**

I am getting missing module errors during alternative windows installation. I am using recent release QualCoder-2.9. Also, this link is broken https://github.com/ccbogel/QualCode because its missing the r in the link.

**To Reproduce**

Put qualcoder folder in downloads directory and follow alternative windows installation to py -m qualcoder

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

![image](https://user-images.githubusercontent.com/40770170/155856982-30eb7366-aeb0-40d5-ac0c-50b5f0f55938.png)

**Desktop (please complete the following information):**
 Windows 10 Home
 21H2
**Additional context**

**Comment by ccbogel** [comment]
Fixed the link wording.

The above screenshot shows that python 3.9 version is being used.

What happens when you install the Qt5 module?
It is possible that you have multiple python versions installed and that it is installing pyqt5 for a different version
`py -m pip install pyqt5`

You can tell pip to install the module for python 3.9 with the below instruction line:
`py -3.9 -m pip install pyqt5` 

If this works then you should use apply the same approach o installing all the python modules with the -3.9 instruction.

**Comment by ccbogel** [comment]
Ok. Try installing QualCoder using from the QualCoder-master or QualCoder-2.9 folder:
py -3.9 setup.py install 
Then 
py -3.9 -m qualcoder

**Comment by agsolbe2** [comment]
![image](https://user-images.githubusercontent.com/40770170/155894752-a8882c0e-b210-4b66-abc7-eb7cfe4a573d.png)

I am getting this traceback from earlier. Here is a screenshot of my environment variables below if this is helpful.

![image](https://user-images.githubusercontent.com/40770170/155895146-4bb34bdc-36a8-4817-ae9a-94c2eb6e6f20.png)

**Comment by ccbogel** [comment]
This is odd. It says with pip that PyQt5 is installed but then cannot find it.

Can you open a python console:
py  or python
then try:
from PyQt5 import QtCore

**Comment by agsolbe2** [comment]
I think I had messed something with my path beforehand or something else, but I got it to work by uninstalling my python and reinstalling it to python 3.10. I think it must've been something with the path or possibly another part of python interfering with it that I might have messed up when tinkering with the files. Anyways it works now after a reinstall of python.
