### ISSUE TITLE
The ArchLinux Installation guide of Readme maybe unintentially be reverted

### ISSUE THREAD

**Issue by FantasqueX** [ccbogel/QualCoder#635]
#630 PR is reverted due to updating to Qt6 which is a mistake in my opinion. I want to know whether it is a mistake or not. If it is a mistake I would like to create a PR to fix it.

**Comment by ccbogel** [comment]
Hello. I dont understand the issue: PR is reverted.
 But yes the upcoming 3.0 version and future versions will be using qt6. The current release QualCoder 2.9 uses qt5. If qt6 does not work on Arch, i can delete those install instructions.
One of the reasons I want to use qt6 is potentially moving away from the requirement to use VLC, as qt6 has apparently better media integration. Occassionally there are install issues due to the need to have VLC and also wrong VLC types installed. (32 vs 64 bit versions ).

**Comment by FantasqueX** [comment]
I actually agree with upgrading to Qt6. The problem is what I did in PR #630 is reverted.More specifically, I think installing pdfminer.six using pacman is the correct way. This is a problem irrelevant with upgrading to Qt6.

**Comment by ccbogel** [comment]
Yes ok. Can you create the fix in the dev_charts branch. This branch is also now importing the packages: pandas and plotly
