### ISSUE TITLE
Multiple Code relations

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#686]
From Andrzej: Relation types: additional option to switch the calculation method from the current to SQL and vice versa.

For example. let's say that we have code A, B, and C. And you selecting these three codes and select "E" relation. The result is:

NOW:

    segments exactly overlapping and coded by A and B and C,
    by A and B,
    by B and C,
    by A and C.

IN PROPOSED SQL:

    exactly overlapping and ONLY segments coded by A and B and C at the same time. So, segments coded only by two out of three selected codes will be not shown.

So. there is need for option to showing only segments which are at the same time coded by ALL selected codes. If you have codes "dogs", "happy", "from Poland", very often you would seek only for segments about dogs which are at the same time 1) dogs, 2) happy, 3) and from Poland. However, current calculation method does not allow for this, because it will show you also happy dogs, but not from Poland, or dogs from Poland, but not happy.

SQL above was written for the case, that user selects "O"relationship, however, here is the version for "E:

SELECT code_relations.Fid , Code0_name, Code0, Code0_pos0, Code0_pos1, Code1_name, Code1, Code1_pos0, Code1_pos1, Relation, ctid0, ctid1, text0, Text_overlap, text1,
ctcode0.memo as "memo0", code_text.memo as "memo1"
FROM code_relations left join code_text on code_text.ctid = ctid1 -- CHANGE TO ctid = ctidCode1 to show memos for code number3
left join code_text as ctcode0 on ctcode0.ctid=ctid0

WHERE
Relation = "E" --OPTION1: SLECT KIND OR KINDS OF RELATION(S)

--AND Fid = 1 --OPTION 2: SELECT FILE OR FILES

AND -- OPTION3: SELECT CODES (CHANGE NUMBER OF CODES IN ALL "Code0 =" and "Code1 =")
(
ctid0 IN
(SELECT ctid0 FROM code_relations WHERE Code0 = 3 AND Code1 = 2 AND Relation= "E" AND ctid1 IN -- 3-2
(SELECT ctid0 FROM code_relations WHERE Code0= 2 AND Code1 = 1 AND Relation= "E" AND ctid1 IN -- 2-1
(SELECT ctid1 FROM code_relations WHERE Code0=3 AND Code1 = 1 AND Relation = "E")) -- 1-3

AND ctid0 IN
(SELECT ctid0 FROM code_relations WHERE Code0= 3 AND Code1 = 1 AND Relation= "E" AND ctid1 IN -- 3-1
(SELECT ctid1 FROM code_relations WHERE Code1 = 1 AND Code0 = 2 AND Relation = "E" AND ctid0 IN -- 1-2
(SELECT ctid1 FROM code_relations WHERE Code1= 2 AND Code0 = 3 AND Relation = "E") -- 2-3
)
)
)

-- TO SHOW ALSO RELATION BETWEEN CODE 2 AND CODE 1
OR ctid0 IN
(SELECT ctid0 FROM code_relations WHERE Code0 = 2 AND Code1 = 1 AND Relation= "E" AND ctid1 IN -- 2-1
(SELECT ctid1 FROM code_relations WHERE Code0= 3 AND Code1 = 1 AND Relation= "E" AND ctid0 IN -- 1-3
(SELECT ctid0 FROM code_relations WHERE Code0=3 AND Code1 = 2 AND Relation = "E")) -- 3-2

AND ctid0 IN
(SELECT ctid1 FROM code_relations WHERE Code0= 3 AND Code1 = 2 AND Relation= "E" AND ctid0 IN -- 2-3
(SELECT ctid0 FROM code_relations WHERE Code1 = 1 AND Code0 = 3 AND Relation = "E" AND ctid1 IN -- 3-1
(SELECT ctid1 FROM code_relations WHERE Code1= 1 AND Code0 = 2 AND Relation = "E") -- 1-2
)
)
)
)

ORDER BY ctid0 ASC -- OPTION 4: SORT BY (ASC, DESC)

-- GROUP BY ctid0 -- OPTION 5: SHOW LESS ROWS (also allow for showing only one row for each comparison)

AND FOR I:

SELECT code_relations.Fid , Code0_name, Code0, Code0_pos0, Code0_pos1, Code1_name, Code1, Code1_pos0, Code1_pos1, Relation, ctid0, ctid1, text0, Text_overlap, text1,
ctcode0.memo as "memo0", code_text.memo as "memo1"
FROM code_relations left join code_text on code_text.ctid = ctid1 -- CHANGE TO ctid = ctidCode1 to show memos for code number3
left join code_text as ctcode0 on ctcode0.ctid=ctid0

WHERE
Relation = "I" --OPTION1: SLECT KIND OR KINDS OF RELATION(S)

--AND Fid = 1 --OPTION 2: SELECT FILE OR FILES

AND -- OPTION3: SELECT CODES (CHANGE NUMBER OF CODES IN ALL "Code0 =" and "Code1 =")
(
ctid0 IN
(SELECT ctid0 FROM code_relations WHERE Code0 = 3 AND Code1 = 2 AND Relation= "I" AND ctid1 IN -- 3-2
(SELECT ctid0 FROM code_relations WHERE Code0= 2 AND Code1 = 1 AND Relation= "I" AND ctid1 IN -- 2-1
(SELECT ctid1 FROM code_relations WHERE Code0=3 AND Code1 = 1 AND Relation = "I")) -- 1-3

AND ctid0 IN
(SELECT ctid0 FROM code_relations WHERE Code0= 3 AND Code1 = 1 AND Relation= "I" AND ctid1 IN -- 3-1
(SELECT ctid1 FROM code_relations WHERE Code1 = 1 AND Code0 = 2 AND Relation = "I" AND ctid0 IN -- 1-2
(SELECT ctid1 FROM code_relations WHERE Code1= 2 AND Code0 = 3 AND Relation = "I") -- 2-3
)
)
)

-- TO SHOW ALSO RELATION BETWEEN CODE 2 AND CODE 1
OR ctid0 IN
(SELECT ctid0 FROM code_relations WHERE Code0 = 2 AND Code1 = 1 AND Relation= "I" AND ctid1 IN -- 2-1
(SELECT ctid1 FROM code_relations WHERE Code0= 3 AND Code1 = 1 AND Relation= "I" AND ctid0 IN -- 1-3
(SELECT ctid0 FROM code_relations WHERE Code0=3 AND Code1 = 2 AND Relation = "I")) -- 3-2

AND ctid0 IN
(SELECT ctid1 FROM code_relations WHERE Code0= 3 AND Code1 = 2 AND Relation= "I" AND ctid0 IN -- 2-3
(SELECT ctid0 FROM code_relations WHERE Code1 = 1 AND Code0 = 3 AND Relation = "I" AND ctid1 IN -- 3-1
(SELECT ctid1 FROM code_relations WHERE Code1= 1 AND Code0 = 2 AND Relation = "I") -- 1-2
)
)
)
)

ORDER BY ctid0 ASC -- OPTION 4: SORT BY (ASC, DESC)

-- GROUP BY ctid0 -- OPTION 5: SHOW LESS ROWS (also allow for showing only one row for each comparison)

**Comment by AndrzejWawa** [comment]
Hi, I recreated issues from the advancing code relations. However, some issues are related to this, namely (number of relations with ALL codes, AND NOT function, as well as show less rows). So, firstly, this issue should be solved.

**Comment by AndrzejWawa** [comment]
I think that the good starting points (and most important) is providing possibility of showing only segments exactly coded by ALL of the selected codes. Here you have SQL statement:

SELECT code_name.name as "codename", code_text.cid, code_text.fid, source.name, code_text.pos0, code_text.pos1, code_text.seltext, code_text.memo as "coding memo" from code_name join code_text on code_name.cid = code_text.cid join source on source.id = code_text.fid
WHERE
code_text.cid IN
(SELECT cid FROM code_text WHERE cid = "1" OR cid = "2") -- INSERT ID's OF THE SELECTED CODES, INSERT "--" AT THE BEGINNING TO SHOW ALL OVERLAPPING CODINGS, NOT ONLY THE SELECTED (ID's for codes can be found in reports => code summary,by inserting SQL statement: SELECT cid, name FROM code_name or selecting "show IDs" in settings to show them in coding text)
-- ADD MORE CODES BY ADDIND "OR CID =" INSERTING NAMES OF ADDITIONAL CODE IN THE PARENTHESES
AND fid = "1" --INSERT ID OF FILE (ID's for file can be found in reports => file summary, by inserting SQL statement: SELECT id, name FROM source, or by or selecting "show IDs" in settings to show them in manage files). WARNING!!!: EVERYWHERE THERE SHOULD BE INSERTED THE SAME, ONLY ONE FILE, OTHERWISE, THE RESULTS CAN BE INCORRECT!!!
AND pos0 IN
(SELECT pos0 FROM code_text WHERE cid = "1" AND fid = "1") --INSERT ID's OF THE FIRST OBLIGATO0RY CODE FOR THE CODINGS
AND pos1 IN
(SELECT pos1 FROM code_text WHERE cid = "1" AND fid = "1")
AND pos0 IN
(SELECT pos0 FROM code_text WHERE cid = "2" AND fid = "1") --INSERT ID's OF THE FIRST OBLIGATO0RY CODE FOR THE CODINGS
AND pos1 IN
(SELECT pos1 FROM code_text WHERE cid = "2" AND fid = "1")
-- ADD MORE CODES IF NEEDED BY COPYING STATEMENTS AND INSERTING NAMES OF ADDITIONAL CODE
-- AS A RESULT YOU OBTAINS LIST OF CODINGS WITH CODING MEMOS WHICH ARE CODED (IN THE SAME RANGE OF CHARACTERS) AT LEAST BY THE SELECTED CODES
-- AND NOT pos0 IN -- REMOVE "--" BEFORE STATEMENTS AND INSERT ID's OF CODE(S) TO EXCLUDE CODINGS WITH SOME CODES
-- (SELECT pos0 FROM code_text WHERE cid = "CODEID3" AND fid = "FILEID1")
-- AND NOT pos1 IN
-- (SELECT pos1 FROM code_text WHERE cid = "CODEID3 AND fid = "FILEID1")
-- OR pos0 IN -- REMOVE "--" BEFORE STATEMENTS AND INSERT ID's OF CODE(S) TO PROVIDE FACULTATORY CODES FOR LOOKINGS CODINGS
-- (SELECT pos0 FROM code_text WHERE cid = "CODEID4" AND fid = "FILEID1")
-- OR pos1 IN
-- (SELECT pos1 FROM code_text WHERE cid = "CODEID4" AND fid = "FILEID1")
-- GROUP BY pos0 -- DELETE "--" TO HIDE DUPLICATES OF UNIONED (EXACTLY OVERLAPPING) CODINGS, WITH CODING MEMOS FOR THE ALPHABETICALLY FIRST CODE (CODING)

**Comment by AndrzejWawa** [comment]
Hi,

Can you place this query in the default queries? It shows exactly overlapping codings by 3 or more codes. but only in one selected file. I think that could be helpful for many people who want categorise fragments by at least 3 codes and searching results (e.g. age, gender, city):

3 OR MORE EXACTLY OVERLAPPING CODINGS 

	SELECT  code_name.name as "codename", code_text.cid,  code_text.fid, source.name, code_text.pos0, code_text.pos1,  code_text.seltext, code_text.memo as "coding memo"  from  code_name join  code_text on  code_name.cid = code_text.cid join source on source.id = code_text.fid

	WHERE 
	
	code_text.cid IN 

	(SELECT cid FROM code_text WHERE cid = "1" OR cid = "2" OR cid = "3") -- INSERT ID's OF THE SELECTED CODES, INSERT "--" AT THE BEGINNING TO SHOW ALL OVERLAPPING CODINGS, NOT ONLY THE SELECTED (ID's for codes can be found in reports => code summary,by inserting SQL statement: SELECT cid, name FROM code_name or selecting "show IDs" in settings to show them in coding text)

-- ADD MORE CODES BY ADDIND "OR CID =" INSERTING NAMES OF ADDITIONAL CODE IN THE PARENTHESES

	AND  fid = "1" --INSERT ID OF FILE (ID's for file can be found in reports => file summary, by inserting SQL statement: SELECT id, name FROM source, or by or selecting "show IDs" in settings to show them in manage files). WARNING!!!: EVERYWHERE THERE SHOULD BE INSERTED THE SAME, ONLY ONE FILE, OTHERWISE, THE RESULTS CAN BE INCORRECT!!!

	AND pos0 IN 
	(SELECT  pos0 FROM code_text WHERE cid = "1" AND fid = "1") --INSERT ID's OF THE FIRST OBLIGATO0RY CODE FOR THE CODINGS
	AND pos1 IN 
	(SELECT  pos1 FROM code_text WHERE cid = "1" AND fid = "1")

	AND pos0 IN
	(SELECT  pos0 FROM code_text WHERE cid = "2" AND fid = "1") --INSERT ID's OF THE SECOND OBLIGATO0RY CODE FOR THE CODINGS
	AND pos1 IN
	(SELECT  pos1 FROM code_text WHERE cid = "2" AND fid = "1")

	AND pos0 IN
	(SELECT  pos0 FROM code_text WHERE cid = "3" AND fid = "1") --INSERT ID's OF THE THIRD OBLIGATO0RY CODE FOR THE CODINGS
	AND pos1 IN
	(SELECT  pos1 FROM code_text WHERE cid = "3" AND fid = "1")

-- ADD MORE CODES IF NEEDED BY COPYING STATEMENTS AND INSERTING NAMES OF ADDITIONAL CODE
-- AS A RESULT YOU OBTAINS LIST OF CODINGS WITH CODING MEMOS WHICH ARE CODED (IN THE SAME RANGE OF CHARACTERS)  AT LEAST BY THE SELECTED CODES

--	AND NOT pos0 IN				-- REMOVE "--" BEFORE STATEMENTS AND INSERT ID's OF CODE(S) TO EXCLUDE CODINGS WITH SOME CODES
--	(SELECT  pos0 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")
--	AND NOT pos1 IN
--	(SELECT  pos1 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")

--	OR pos0 IN				-- REMOVE "--" BEFORE STATEMENTS AND INSERT ID's OF CODE(S) TO PROVIDE FACULTATORY CODES FOR LOOKINGS CODINGS 
--	(SELECT  pos0 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")
--	OR pos1 IN
--	(SELECT  pos1 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")



-- GROUP BY pos0 -- DELETE "--" TO HIDE DUPLICATES OF UNIONED (EXACTLY OVERLAPPING) CODINGS, WITH CODING MEMOS FOR THE ALPHABETICALLY FIRST CODE (CODING)

**Comment by AndrzejWawa** [comment]
Hi,

Can you place this query in the default queries? It shows exactly overlapping codings by 3 or more codes. but only in one selected file. I think that could be helpful for many people who want categorise fragments by at least 3 codes and searching results (e.g. age, gender, city):

3 OR MORE EXACTLY OVERLAPPING CODINGS 

	SELECT  code_name.name as "codename", code_text.cid,  code_text.fid, source.name, code_text.pos0, code_text.pos1,  code_text.seltext, code_text.memo as "coding memo"  from  code_name join  code_text on  code_name.cid = code_text.cid join source on source.id = code_text.fid

	WHERE 
	
	code_text.cid IN 

	(SELECT cid FROM code_text WHERE cid = "1" OR cid = "2" OR cid = "3") -- INSERT ID's OF THE SELECTED CODES, INSERT "--" AT THE BEGINNING TO SHOW ALL OVERLAPPING CODINGS, NOT ONLY THE SELECTED (ID's for codes can be found in reports => code summary,by inserting SQL statement: SELECT cid, name FROM code_name or selecting "show IDs" in settings to show them in coding text)

-- ADD MORE CODES BY ADDIND "OR CID =" INSERTING NAMES OF ADDITIONAL CODE IN THE PARENTHESES

	AND  fid = "1" --INSERT ID OF FILE (ID's for file can be found in reports => file summary, by inserting SQL statement: SELECT id, name FROM source, or by or selecting "show IDs" in settings to show them in manage files). WARNING!!!: EVERYWHERE THERE SHOULD BE INSERTED THE SAME, ONLY ONE FILE, OTHERWISE, THE RESULTS CAN BE INCORRECT!!!

	AND pos0 IN 
	(SELECT  pos0 FROM code_text WHERE cid = "1" AND fid = "1") --INSERT ID's OF THE FIRST OBLIGATO0RY CODE FOR THE CODINGS
	AND pos1 IN 
	(SELECT  pos1 FROM code_text WHERE cid = "1" AND fid = "1")

	AND pos0 IN
	(SELECT  pos0 FROM code_text WHERE cid = "2" AND fid = "1") --INSERT ID's OF THE SECOND OBLIGATO0RY CODE FOR THE CODINGS
	AND pos1 IN
	(SELECT  pos1 FROM code_text WHERE cid = "2" AND fid = "1")

	AND pos0 IN
	(SELECT  pos0 FROM code_text WHERE cid = "3" AND fid = "1") --INSERT ID's OF THE THIRD OBLIGATO0RY CODE FOR THE CODINGS
	AND pos1 IN
	(SELECT  pos1 FROM code_text WHERE cid = "3" AND fid = "1")

-- ADD MORE CODES IF NEEDED BY COPYING STATEMENTS AND INSERTING NAMES OF ADDITIONAL CODE
-- AS A RESULT YOU OBTAINS LIST OF CODINGS WITH CODING MEMOS WHICH ARE CODED (IN THE SAME RANGE OF CHARACTERS)  AT LEAST BY THE SELECTED CODES

--	AND NOT pos0 IN				-- REMOVE "--" BEFORE STATEMENTS AND INSERT ID's OF CODE(S) TO EXCLUDE CODINGS WITH SOME CODES
--	(SELECT  pos0 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")
--	AND NOT pos1 IN
--	(SELECT  pos1 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")

--	OR pos0 IN				-- REMOVE "--" BEFORE STATEMENTS AND INSERT ID's OF CODE(S) TO PROVIDE FACULTATORY CODES FOR LOOKINGS CODINGS 
--	(SELECT  pos0 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")
--	OR pos1 IN
--	(SELECT  pos1 FROM code_text WHERE cid = "CODEID" AND fid = "FILEID1")



-- GROUP BY pos0 -- DELETE "--" TO HIDE DUPLICATES OF UNIONED (EXACTLY OVERLAPPING) CODINGS, WITH CODING MEMOS FOR THE ALPHABETICALLY FIRST CODE (CODING)

**Comment by ccbogel** [comment]
I am thinking these are getting to be too complex as default queries.

I think extending the code relations report , or having another report that covers this would be better.

**Comment by AndrzejWawa** [comment]
> I am thinking these are getting to be too complex as default queries.
> 
> I think extending the code relations report , or having another report that covers this would be better.

Yes, think that the code relations report is a natural place.

**Comment by ccbogel** [comment]
OK. There is a new button. it exports an Excel file.
It does all text files and all matching coded text segments in each file (2 or more matches)
It is ordered for filename and within the filename, then the code names

**Comment by AndrzejWawa** [comment]
Can you show results also in QC, not only in exported file?

**Comment by ccbogel** [comment]
I think there is enough options in there now if you select exact in the drop down box and select all the codes you are interested in in the code tree.

**Comment by AndrzejWawa** [comment]
Hi, I checked and I meant sth different.

In the example below I coded the word "university" by code 1, 2, and 3, but the word "Canada" I coded only by code 1 and 2. When I select exact and code 1, 2, and 3 in the code tree the result is:

![obraz](https://user-images.githubusercontent.com/77200214/227680164-d9d9cc95-4e52-4083-bf41-516ea5b989a5.png)

But I want only word "university" to be displayed, because only this word was coded by three of codes. So, I meant the result which is obtained by proposed SQL:

![obraz](https://user-images.githubusercontent.com/77200214/227680262-d244475b-7f67-46dd-9738-259839d47ff3.png)

Is it possible to implement this SQL after selecting more than 2 code in the code tree? It could be provided option between operators "OR" and "AND", where AND provides result as the SQL.

**Comment by ccbogel** [comment]
To be honest, I do not understand what you want, that cannot be already done in Code Relations.
I have added that sql query to the Database Default Queries and I have edited it for better readability.

The statements at the end do not make a lot of sense:
Why have this?
-- REMOVE "--" BEFORE STATEMENTS AND INSERT IDs OF CODES
-- OR pos0 IN (SELECT pos0 FROM code_text WHERE cid=CODEID AND fid=1) 
-- OR pos1 IN (SELECT pos1 FROM code_text WHERE cid=CODEID AND fid=1) 

![Screenshot from 2023-03-26 15-39-52](https://user-images.githubusercontent.com/5834638/227755672-edf1fb7b-5fa5-4c99-b8be-9f32d710754e.png)

**Comment by AndrzejWawa** [comment]
Hi, 

Thank you very much! I think it will be very helpful for many users.

**1. When it comes to "AND NOT" option:** 

let's say that we have code tree with three categories of codes (treated as variables) containing the following codes (treated as values of these variables):

Category 1 - gender:
Code 1 - female,
Code 2 - male,
Code 3 - other,
Category 2 - hair colour,
Code 4 - black,
Code 5 - blond,
Code 6 - red,
Code 7 - brown,
Category 3 - living place.
Code 8 -  small village,
Code 9 - big village
Code 10 - small town,
Code 11 - big town,
Code 12 - small city.
Code 13 - big city,
Category 4 - age.
Code 14 - young,
Code, 15 - medium,
Code 16 - old

And suppose you have coded big amount text by these code. Then, you want to display only fragments concerning females, with black hair, and young, but excluding these from big cities. So, it easier select search criteria: 
CID IN CODE 1 AND CODE 4 AND CODE 14, **AND NOT IN** CODE 13, 
than: 
CID IN CODE 1 AND CODE 4 AND CODE 14 AND CODE 8 AND CODE 9 AND CODE 10 AND CODE 11, AND CODE 12.

4. When it comes to OR option:

Let's say that you want obtain fragment concerning young females with black OR blond hair colour:

So, you cannot write:

CID IN CODE 1 AND CODE 14 AND CODE 4 AND CODE 5, because then you will try to find fragments concerning at the same time females with black and blond hair, but it is not possible to have at the same time black and blond hair, so you have to write:

CIDE IN CODE  AND CODE 14 AND (CODE 4 OR CODE 5) - however, I indeed have to correct formula related to OR to achieve this effect.

Now, in code relations report, **you are not able** to filter text segments in this way, because it uses logical operator OR between code so display all possible realtions between selected codes. Moreover, you are not able exclude fragments coded by specific codes or wrap text by pos. 0 to delete duplicates in fragments.

Is it all clear?

**Comment by ccbogel** [comment]
I understand better than I did before. I have updated the sql query here, 
but this final bit I believe would not work correctly...

-- COPY AND PASTE AFTER THE LAST LINE BUT BEFORE THE LAST BRACKET AND FILL THE FOLLOWING FRAGMENT "**OR** (pos0 IN (SELECT pos0 FROM code_text WHERE cid=CODEID AND fid=1) AND pos1 IN (SELECT pos1 FROM code_text WHERE cid=CODEID AND fid=1))" TO ADD MORE ALTERNATIVE CODES

The **OR** should be AND

**Comment by AndrzejWawa** [comment]
Hi,

No, I meant sth different. What you introduced is already introduced in the information:
"-- Add more codes if needed by copying the above two "AND" statements and put cid=THE EXTRA CODE ID for each additional code"

In other words, you meant the logic: CID1 AND CID 2 AND CID 3 **AND CID 4** - but this was already explained.

I meant add option to use logic: CID 1 AND CID 2 AND CID 3 **AND (CID4 OR CID 5)**.

So, this part is correct and what I meant:

-- REMOVE "--" BEFORE STATEMENTS AND INSERT IDs OF CODES TO FIND CODINGS WITH AT LEAST ONE OF TWO (OR MORE) ALTERNATIVE CODES
--AND (
--(pos0 IN (SELECT pos0 FROM code_text WHERE cid=CODEID AND fid=1) AND pos1 IN (SELECT pos1 FROM code_text WHERE cid=CODEID AND fid=1))
--OR (pos0 IN (SELECT pos0 FROM code_text WHERE cid=CODEID AND fid=1) AND pos1 IN (SELECT pos1 FROM code_text WHERE cid=CODEID AND fid=1))
--)
-- COPY AND PASTE AFTER THE LAST LINE BUT BEFORE THE LAST BRACKET AND FILL THE FOLLOWING FRAGMENT "OR (pos0 IN (SELECT pos0 FROM code_text WHERE cid=CODEID AND fid=1) AND pos1 IN (SELECT pos1 FROM code_text WHERE cid=CODEID AND fid=1))" TO ADD MORE ALTERNATIVE CODES

**Comment by ccbogel** [comment]
ok, updated

**Comment by AndrzejWawa** [comment]
Excellent! Thanks.
