### ISSUE TITLE
Coding report problem - unable to select files

### ISSUE THREAD

**Issue by ACR268** [ccbogel/QualCoder#788]
### Discussed in https://github.com/ccbogel/QualCoder/discussions/787

<div type='discussions-op-text'>

<sup>Originally posted by **ACR268** April  4, 2023</sup>
Hello, 

For some reason, I am now unable to run a coding report because none of my 16 files show up on the left where I can select them from. I was able to do it a few hours ago, but then I re-coded some of the data and when I went to run the report again, the files no longer show up.But they are definitely still in the project and all the coded data is there. 
I have tried closing, exiting and reopening, or even opening back-up versions of the project but nothing changes. 

Any suggestions please? 

![image](https://user-images.githubusercontent.com/129871991/229822510-a67f22ca-88b6-44b1-843e-8e28a710b724.png)
</div>

**Comment by ccbogel** [comment]
I did make some changes to the latest code (obtain via green code button, this could be a problem if you obtained and installed the latest code around this time), approximately 1 day ago, that had errors that were fixed about 12 hours later.
Try downloading the latest code again and installing and using again.
If this error still occurs, can you zip your project folder and send to me, so I can test and see where the problem is occurring.

**Comment by ACR268** [comment]
Hello again, 

I did figure it out in the end by re-installing (althought I already had the latest version). Basically, there seem to be two selection panes: a files pane which I am using, and a cases pane below it, which I don't use as I don't have any cases. Somehow I had dragged the cases pane over the files pane and completely covered it and it was impossible to tell, as you can see from the picture above. This viewing set-up remained the same no matter what project I opened, until I reinstalled. A bit of a facepalm moment :) 

![image](https://user-images.githubusercontent.com/129871991/230020137-f41c857a-1065-4160-a23e-0f6cfc1e5d00.png)

Thank you so much for getting back to me!

**Comment by ccbogel** [comment]
Ahh ok. I will have to add in a note about that.
