### ISSUE TITLE
attribute data lost after adding new file

### ISSUE THREAD

**Issue by michaelpalumbo** [ccbogel/QualCoder#805]
**Describe the bug**
attribute data lost after adding new file

**To Reproduce**
Create a new file, enter data in custom attribute fields, then create a new file and after adding the text in that file and clicking 'ok', the attribute data in the previous file is now missing. 

**Expected behavior**
the data, after being entered, remains in the fields and doesn't disappear. 

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version: Ventura 13.4.1

**Additional context**
Built from source version 3.2

**Comment by ccbogel** [comment]
Ok I can recreate this. I am using the 3.4 version. I find going to the Files and Cases menu and selecting Manage Files repopulates the missing attribute data. 
It must be something to do with the table display - Im working on it.

**Comment by ccbogel** [comment]
OK. I have fixed this, according to my testing, anyways.
Download and use the latest code for the 3.4 version using the green code download button: https://github.com/ccbogel/QualCoder

Build again. There might be some new python modules to install, see below instructions in the same page. e.g. xmlschema module

Let me know if this fixes the issue. and hope otherwise QualCoder is working well for you.
