### ISSUE TITLE
Warning of attribute names that use reserved strings not easily intelligible

### ISSUE THREAD

**Issue by ilippert** [ccbogel/QualCoder#815]
**Describe the bug**
Once an attribute with a name X is created, removed, it cannot be added again.

**To Reproduce**

1. Enter `manage attributes`
2. add a new attribute `DATE` of type `character` 
3. remove the attribute `DATE`
4. try to add a new attribute `date`

**Expected behavior**
I would expect it is possible to add the new attribute; but instead I get an error message.

![Screenshot from 2023-08-23 09-42-33](https://github.com/ccbogel/QualCoder/assets/20518297/639d4a10-0af6-49db-a9c0-2ff5dd2d4a11)

The screenshot shows, too, that behind the windows, QualCoder does not indicate that the attribute would still exist.

**Comment by ccbogel** [comment]
Yes, I have a short list of names that I thought could cause problems (as they match some table columns for data that is not Attributes), below: 
name memo id date Ref_Type Ref_Author Ref_Title Ref_Year jid Coder Name Modified

I warn the user with the above warning.
1 - I will improve the warning wording
2 - I will review if some of these names can be removed from the 'reserved words' list for attribute names.

**Comment by ilippert** [comment]
Hmm, just to ensure you note this: I was successfully able to add an attribute called `DATE`once.

**Comment by ccbogel** [comment]
I have updated the code now. So the warning is better.
I have checked using other names that I thought might be a problem, such as _date_. I have found that there is no problem with adding this now.
So essentially all the issues raised have been resolved now.

One more thing - and this is historical, based on how I set up the QualCoder database (so I cannot change it now, as it would affect too many people). One an attribute name is assigned to cases, files or journals, the exact same name cannot be used again elsewhere.  So journals with a _date_ attribute is OK, but you cannot use the exact same worded _date_ in files.
This is because the attribute_type table uses the attribute name as a primary key - and so all attribute names must be unique.

**Comment by ccbogel** [comment]
@ilippert I did have the wiki open to all at one time. But a malicious person edited some links to go to scam sites. So I cannot open the wiki to all anymore. I am not an organisation so I cannot add you as a collaborator, from what I read about github.
Instead, you could copy a wiki page as html, load in Word or LOffice - make edits in Word or LibreOffice (highlighted) then send me those updates so I can update the wiki.
