### ISSUE TITLE
Error when i import survey

### ISSUE THREAD

**Issue by qwertygc** [ccbogel/QualCoder#83]
Hello !

I have a survey, with press articles. My CSV is uniq ID, name of newspaper, date and content.
When i import, i have error :

```
Traceback (most recent call last):
  File "/usr/share/qualcoder/import_survey.py", line 234, in accept
    self.insert_data()

  File "/usr/share/qualcoder/import_survey.py", line 292, in insert_data
    if self.fields_type[col] != "qualitative":

IndexError: list index out of range
```
![image](https://user-images.githubusercontent.com/4261986/85304173-bce8c480-b4ab-11ea-9360-7f645ad75e44.png)

**Comment by ccbogel** [comment]
Hello qwertgc,
I made a csv file with this format and content:
The comma separates each field
The quotation marks " "  contain text with commas in one field.
I have made this file so that the quotation marks are only in one column, so the MINIMAL quote format should be chosen.

id,date,journal,Content
ID1,2013-03-18,Le_monde,"Fractuartion"
ID2,2013-03-18,le_monde,"La France, commas here, and, commas"
ID3,2009-07-01,enironment,"Le retour"

The Quote format is important when importing. The other options should be MINIMAL and ALL. 

![scre1](https://user-images.githubusercontent.com/5834638/85344152-2f03ec80-b532-11ea-9ef8-fc7acbb6d9e8.png)

Some elements may have imported so delete these from your project (files and cases) or if you have only just started, then begin a new project and import into that.

Another issue with comma/quote csv files, is if you have a quotation mark within your Content text this could be a problem, so remove or replace with another mark, before importing.

**Comment by ccbogel** [comment]
Also. I have updated the import_survey.py code, so that it warns the user of a possible error from the quote format.

**Comment by qwertygc** [comment]
Think you for you reponse, it's work with ALL quote format !

Other question, I can't code text of a csv file (the field "Content") ?

**Comment by qwertygc** [comment]
It'es perfect, it's work perfectly :+1:
