### ISSUE TITLE
Word cloud for specific categories

### ISSUE THREAD

**Issue by amru39** [ccbogel/QualCoder#859]
Would it possible to create word clouds for specific category or categories instead of entire text? Or alternatively have the option to exclude certain words/non-verbal sounds (umm, hmmm etc.) from the word cloud?

**Comment by ccbogel** [comment]
Sure, I will look into making it better.

**Comment by amru39** [comment]
Thank you. I am sure you spend a lot of time on responding to the requests. Really appreciate it.

**Comment by ccbogel** [comment]
Thats OK. I have to look at the wordcloud code closely. as I am not 100% happy with including it into QualCoder. As I cannot make exe files with the wordcloud module present.

**Comment by ccbogel** [comment]
I am working on integrating Andreas's wordclould module into QualCoder. So I will be able to create exe / executable files, and also to add that function you want to add specific stop words.

**Comment by ccbogel** [comment]
@amru39 you can now add your own stopwords list. make a text file called stopwords.txt Each line in the file is a word to be excluded. Put this file in the .qualcoder folder  This is located in Users/yourusername/.qualcoder
There is a list of English stopwords used in qualcoder now, but you can edit or make your own. Some lists in other languages are here: https://github.com/Alir3z4/stop-words

**Comment by amru39** [comment]
Thank you. This is great. Umm, Uh-huh, etc. were the most prominent words in the word coulds I generated previously and now they just don't show up. 

Do you think it is possible/feasible to have this feature for those doing a command prompt installation and not include it in the .exe version?

**Comment by ccbogel** [comment]
I am working on my own version of wordcloud. It wont be as sophisticated as the one created by Andreas Mueller, But it should not have problems with compiling. I have attached examples:

![img2](https://github.com/ccbogel/QualCoder/assets/5834638/a014c781-58ec-4b4b-9e8e-dad2f9650ebd)

![img](https://github.com/ccbogel/QualCoder/assets/5834638/a31fdc53-2110-42c2-a746-a70a766f91b8)

**Comment by ccbogel** [comment]
updated

**Comment by amru39** [comment]
Thank you!! This is really great. 

Is the third box to limit number of words? And the fourth box? 

Will stopwords work with this version? 
![image](https://github.com/ccbogel/QualCoder/assets/115567313/d0381f45-d7fc-4df8-8ad9-438d4abc7efd)

**Comment by ccbogel** [comment]
@amru39 Hi. The third box is to limit the number of words. 
The 4th box the tick box is to reverse the colour range. This is when you select a colour range option and maybe want green to blue from big to small words, instead of blue to green.
I see you are using a larger font size - this means all the label text (e.g. Max words) do not fit inside the label box. What font size are you using? 
I am using a general font size of 10.

Stopwords will work with this version. put a stopwords.txt file in the .qualcoder folder.
If the file is not there it will use a list of ones I have made within the software. I will put this list as a stopwords.txt in the examples folder also.

Once a wordcloud is made it is saved to your Downloads folder.

Experiment with is and let me know what you think.

**Comment by amru39** [comment]
It is working perfectly. I tried different options and did not run into any issue. The only change I would like (though not a big deal) is the word cloud getting saved in the project folder and not in Downloads.

**Comment by ccbogel** [comment]
OK, I have changed this. so now you will be asked where to save the word cloud
