### ISSUE TITLE
minor visual issues

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#93]
Nothing critical but for completeness here are a few visual issues I noticed. 
* The settings dialogue still has the '?' (top-right corner) -- see screenshot
* I don't see how I can get consistent font sizes in different dialogues across the application. Eg see screenshot
* The application could remember preferred window/pane sizes (eg text area in Code Text), widths of columns in various places (eg the Code Name and Memo column in the code tree which doesn't work well with long code names). 
* As I hover moving from menu to menu on the toolbar, the menu I move away from doesn't lose its shading -- see second screenshot. 

![scr](https://user-images.githubusercontent.com/16408198/86820195-3b329280-c078-11ea-846a-321e4b9a4a5f.png)

![scr2](https://user-images.githubusercontent.com/16408198/86820194-3a99fc00-c078-11ea-89d5-29fa43e89942.png)

**Comment by ccbogel** [comment]
I have updated and remove the 'whats this' question mark for Windows OS for the Settings dialog.

I don't see how I can get consistent font sizes in different dialogues across the application. Eg see screenshot. 
Not sure of the issue here.  You can select different font types and sizes.

The application could remember preferred window/pane sizes (eg text area in Code Text), widths of columns in various places (eg the Code Name and Memo column in the code tree which doesn't work well with long code names).
Yes - I will consider doing this  later on.

As I hover moving from menu to menu on the toolbar, the menu I move away from doesn't lose its shading -- see second screenshot.
Yes I noticed this issue also, but does not affect anything, and I am not sure how to resolve. the menu item under my mouse is a pale blue colour.

**Comment by glocalglocal** [comment]
On fonts: In the image below, I selected a font size that makes eg 'Project' consistent with my system, but then the font for 'This coder name' and similar text in other dialogues becomes too small. If I increase the size, menu fonts etc become fat too big. Not a huge problem but it looks odd. 

![fonts](https://user-images.githubusercontent.com/16408198/86853856-db071500-c0a6-11ea-984e-0720dedc6026.png)

**Comment by ccbogel** [comment]
yes- I understand now. Yes it is a small issue. Can you live with this as is?
Another option which will take some more work would be to add a font and size box in the Settings for menu headings. But I dont particularly want to do this for a small visual issue.

**Comment by glocalglocal** [comment]
Not a problem. I just report as many issues as I see for the record since I started.

**Comment by ccbogel** [comment]
OK thanks. You have been extremely helpful in testing and uncovering things that I missed. My RQDA database was not original I generated it to try and match the real one, so that's why a few issues occurred there.

**Comment by glocalglocal** [comment]
The 'whats this' question mark still appears in the View file dialogue.

**Comment by ccbogel** [comment]
fixed this one
