### ISSUE TITLE
Remember window and column sizings

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#95]
The application could remember preferred window/pane sizes (eg text area in Code Text), widths of columns in various places (eg the Code Name and Memo column in the code tree which doesn't work well with long code names).

**Comment by ccbogel** [comment]
A challenge. However most dialogs now store their last settings. The width and height are stored in the config.ini file.
I cannot do this for the widths of columns in the tree - they seem to be set and likely dont have a resize event.

**Comment by glocalglocal** [comment]
I am assuming the column is given the min width necessary to fit the longest string. 

In Manage Cases, I move the vertical divider to the left to create more space for texts. I close and re-open the dialogue -- the divider is where I left it. But if I close, open/close another dialogue, and re-open Manage Cases, the divider is reset. 

All this means that some dialogues cannot be made smaller even if there is far too much white space, because the buttons are made extra wide.

**Comment by ccbogel** [comment]
I have not coded anything regards the divider. Only the size of the entire dialog. As I thought that was what you meant. 
The main window i did not complete adding code for this yet. But can. 
There is a lot of space in the buttons. Its needed for other languages. But i could have more rows of buttons reducing the horizontal space and so allowing for narrower dialogs.
I have not tried thus yet, but for long code names add a linebreak of \n this may show the code over several kines instead of being really long horizontally.

**Comment by glocalglocal** [comment]
'I have not coded anything regards the divider.' How come it remembers the new divider position when I re-open it? I suppose a variable holds its new value but it is not saved in the ini then. I think as much of the environment as possible should be remembered. Otherwise, for example, the divider positioned in the middle generates too much white space in the left pane. 

Some standard buttons are far too big. Eg Add and Delete in Manage Attributes. Not sure how localisation is dealt with in these cases, but I can't imaging 'Add' taking that much space in any language. Do people provide for localisation by adjusting sizes dynamically perhaps?

**Comment by ccbogel** [comment]
I didn't realise the divider remembered the position when reopening.  I will have to look at this in action soon. It might be that some background variable in the qt framework does this.
I havent done anything with dynamic adjustments.  
If some buttons are far too big, will look at those.

**Comment by ccbogel** [comment]
Currently working on remembering the splitter (divider) positions.

**Comment by ccbogel** [comment]
completed the splitter (divider) saving

**Comment by glocalglocal** [comment]
The splitter in coding reports and SQL statement are not remembered. 

I think the defaults for splitter positions could be set to something more sensible. Eg I may be wrong, but I think the left pane in Manage Cases will almost always be narrower than the right one.

**Comment by ccbogel** [comment]
Fixed splitter sizes in sql dialog.
Im OK with the Manage cases panes - it may help others to see that there are attributes there. But now it can be changed by you to whatever you like, and stay that way.
code frequencies dialog - have made smaller. - let me know of others when they arise.
